### ISSUE TITLE
Exception error inserting a picture in the RTE

### ISSUE THREAD

**Issue by gerathjen** [jweiland-net/jwtools2#68]
When clicking on the button to insert an image in the editor, Typo3 throws the following exception:
![backend-insert-picture-rte](https://user-images.githubusercontent.com/5717825/219034053-6d1bff8b-54ae-46e3-9c10-81f55efc9e47.png)
![backend-exception-insert-picture-rte](https://user-images.githubusercontent.com/5717825/219034002-6c4f852c-a299-4803-9342-cbe647786874.png)

In my opinion, it looks like the jwtools2 extension overwrites the `rte-ckeditor-image`, cf. figure.
![filebrowser](https://user-images.githubusercontent.com/5717825/219034705-83919cbc-b937-4083-907a-f525f0e1cda3.png)

If I disable the jwtools2 extension, I can insert a picture in the RTE. Typo3 10.4.36 with composer is used. The extension is version 6.0.6.

**Comment by sfroemkenjw** [comment]
Hello @gerathjen 

thank you for providing this issue. I just see that having images in CkEditor is another extension. I have just installed rte_ckeditor_image to my TYPO3 12 and activated all image features of jwtools2 and can't reproduce this issue.

We will not solve that issue for TYPO3 10 as templating for BE views can only be realized with XClasses which replaces TYPO3 code. And yes, that may result in such errors. Since TYPO3 12 we are using the much cleaner template API.

There is no free support for TYPO3 10 since april 2024. Please update to at least TYPO3 12 and the problem is solved.

Stefan
